In [1]:
import pandas as pd
import pickle
import numpy as np
import os
from tqdm import tqdm

In [2]:
!pwd

/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network

# loading Ensemble_file

In [3]:
df_ensemble = pd.read_csv('df_ensemble.csv')
df_ensemble

                     0          1
0      ENSG00000210049      MT-TF
1      ENSG00000211459    MT-RNR1
2      ENSG00000210077      MT-TV
3      ENSG00000210082    MT-RNR2
4      ENSG00000209082     MT-TL1
...                ...        ...
70606  ENSG00000232679  LINC01705
70607  ENSG00000200033  RNU6-403P
70608  ENSG00000228437  LINC02474
70609  ENSG00000229463   LYST-AS1
70610  ENSG00000229291  LINC02768

[70611 rows x 2 columns]

In [4]:

def return_ensemble_id(x):
    try:
        return df_ensemble[df_ensemble['1']==x]['0'].values[0]
    except: 
        return np.nan

# Converting CSV to pickle

In [5]:
'''
for i in tqdm(os.listdir('../../usman/Single_Cell_Microglia_Project/preprocessed_data/excitory_neurons/split_chunks/excitory_neurons_2/Exc_L6_THEMIS_NFIA/')):
    
    if '.csv' in i:
        print(i)
        #print(pd.read_csv('../../preprocessed_data/inhibitory_neuron/split_chunks/'+i,nrows=2,index_col=0))
        data = pd.read_csv('../../usman/Single_Cell_Microglia_Project/preprocessed_data/excitory_neurons/split_chunks/excitory_neurons_2/Exc_L6_THEMIS_NFIA/'+i,index_col=0)
        pickle_file_path = '../../usman/Single_Cell_Microglia_Project/preprocessed_data/excitory_neurons/split_chunks/excitory_neurons_2/Exc_L6_THEMIS_NFIA/'+i.split('.')[0]+'.pkl'
        data.to_pickle(pickle_file_path) '''

"\nfor i in tqdm(os.listdir('../../usman/Single_Cell_Microglia_Project/preprocessed_data/excitory_neurons/split_chunks/excitory_neurons_2/Exc_L6_THEMIS_NFIA/')):\n    \n    if '.csv' in i:\n        print(i)\n        #print(pd.read_csv('../../preprocessed_data/inhibitory_neuron/split_chunks/'+i,nrows=2,index_col=0))\n        data = pd.read_csv('../../usman/Single_Cell_Microglia_Project/preprocessed_data/excitory_neurons/split_chunks/excitory_neurons_2/Exc_L6_THEMIS_NFIA/'+i,index_col=0)\n        pickle_file_path = '../../usman/Single_Cell_Microglia_Project/preprocessed_data/excitory_neurons/split_chunks/excitory_neurons_2/Exc_L6_THEMIS_NFIA/'+i.split('.')[0]+'.pkl'\n        data.to_pickle(pickle_file_path) "

# Loading Pickle File

In [6]:

l = 0
for i in os.listdir('../../usman/Single_Cell_Microglia_Project/preprocessed_data/excitory_neurons/split_chunks/excitory_neurons_2/Exc_L6b/'):
    try:
        if i.split('.')[1] == 'pkl':
            print(i)
            pickle_file_path = '../../usman/Single_Cell_Microglia_Project/preprocessed_data/excitory_neurons/split_chunks/excitory_neurons_2/Exc_L6b/' + i
            if l == 0: 
                data = pd.read_pickle(pickle_file_path)
                # to load data in the RAM (not possible to load all data once)
                selected_columns = np.random.choice(data.columns, size=int(len(data.columns) *1), replace=False)
                data = data[selected_columns]
            else:
                df = pd.read_pickle(pickle_file_path)
                df_selected = df[selected_columns] # selected columns comimg from first time loaded data
                data = pd.concat([data,df_selected],axis = 0)
            
            print("Pickle file has been loaded into a DataFrame:")
            l = l + 1       
    except:
        continue

excitory_neurons_mat_chunk_16.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_14.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_2.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_9.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_8.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_5.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_7.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_10.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_4.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_12.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_3.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_1.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_17.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_15.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_6.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_11.pkl
Pickle file has been loaded into a DataFrame:
excitory_neurons_mat_chunk_13.pkl
Pickle file has been loaded into a DataFrame:

In [7]:
data

,GTCGCGAAGAGCCTGA.19.4,CAGCACGGTCACTGAT.25.4,GTAAGTCAGGCCTAAG.8.2,AGGAAATTCTACACAG.25.9,TCTACATCAGACAATA.20.11,GTAGGTTCAGCGTACC.1.3,GGTGATTAGTGCCCGT.26.2,TGCTCGTGTCCAAGAG.29.11,AAGGTAAGTCGCATGC.16.14,CTGTATTTCCGTTGGG.7.9,...,TTGCATTTCACCACAA.22.2,AGGCATTCATAACTCG.3.14,CCTCCTCTCAACCCGG.7.10,ATCAGGTGTGAGACGT.13.3,CAAGACTAGCTCCACG.8.10,TGTTGAGTCGGTGTAT.1.8,GCTACCTTCGTTGCCT.8.9,CGAGGAAAGTAGCATA.21.4,TTCCTAACATCATGAC.20.11,TTGTTTGCATACATCG.15.11
NKAIN4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
AL121827.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ARFGAP1,1,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
COL20A1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
CHRNA4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AC007336.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
MMP2-AS1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LPCAT2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
AC007336.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CAPNS2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Converting Gene Name to Ensemble_id|

In [8]:
x = data.reset_index()['index'].apply(return_ensemble_id)

In [9]:
x.value_counts()

index
ENSG00000256812    1
ENSG00000101198    1
ENSG00000101199    1
ENSG00000101203    1
ENSG00000102924    1
                  ..
ENSG00000101213    1
ENSG00000125508    1
ENSG00000125531    1
ENSG00000130589    1
ENSG00000101216    1
Name: count, Length: 22500, dtype: int64

In [10]:
data['ensemble_gene_name'] = x.tolist()
data = data.dropna()
data

,GTCGCGAAGAGCCTGA.19.4,CAGCACGGTCACTGAT.25.4,GTAAGTCAGGCCTAAG.8.2,AGGAAATTCTACACAG.25.9,TCTACATCAGACAATA.20.11,GTAGGTTCAGCGTACC.1.3,GGTGATTAGTGCCCGT.26.2,TGCTCGTGTCCAAGAG.29.11,AAGGTAAGTCGCATGC.16.14,CTGTATTTCCGTTGGG.7.9,...,AGGCATTCATAACTCG.3.14,CCTCCTCTCAACCCGG.7.10,ATCAGGTGTGAGACGT.13.3,CAAGACTAGCTCCACG.8.10,TGTTGAGTCGGTGTAT.1.8,GCTACCTTCGTTGCCT.8.9,CGAGGAAAGTAGCATA.21.4,TTCCTAACATCATGAC.20.11,TTGTTTGCATACATCG.15.11,ensemble_gene_name
NKAIN4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,ENSG00000101198
ARFGAP1,1,0,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,ENSG00000101199
COL20A1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,ENSG00000101203
CHRNA4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ENSG00000101204
KCNQ2,0,1,1,4,2,3,1,0,1,5,...,0,0,2,2,1,8,5,1,3,ENSG00000281151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
IRX6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ENSG00000159387
MMP2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ENSG00000087245
MMP2-AS1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ENSG00000260135
LPCAT2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,ENSG00000087253
CAPNS2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,ENSG00000256812

In [11]:
data.set_index('ensemble_gene_name', inplace = True)
data = data.T
data

ensemble_gene_name,ENSG00000101198,ENSG00000101199,ENSG00000101203,ENSG00000101204,ENSG00000281151,ENSG00000101210,ENSG00000125534,ENSG00000101213,ENSG00000125508,ENSG00000125531,...,ENSG00000177508,ENSG00000261803,ENSG00000283304,ENSG00000245694,ENSG00000176842,ENSG00000159387,ENSG00000087245,ENSG00000260135,ENSG00000087253,ENSG00000256812
GTCGCGAAGAGCCTGA.19.4,0,1,0,0,0,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CAGCACGGTCACTGAT.25.4,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GTAAGTCAGGCCTAAG.8.2,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AGGAAATTCTACACAG.25.9,0,1,0,0,4,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TCTACATCAGACAATA.20.11,0,0,0,0,2,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TGTTGAGTCGGTGTAT.1.8,0,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GCTACCTTCGTTGCCT.8.9,0,0,0,0,8,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CGAGGAAAGTAGCATA.21.4,0,0,0,0,5,9,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTCCTAACATCATGAC.20.11,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTGTTTGCATACATCG.15.11,0,1,0,0,3,3,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Loading Clinical Data

In [12]:
clinical_data = pd.read_csv('../../danish/preprocessed_data/clinical/clinical_single_cell.csv')
clinical_data

,individualID,individualIdSource,sex,ethnicity,pmi_df2,subject,projid,Study,msex,educ,...,age_death,cts_mmse30_first_ad_dx,cts_mmse30_lv,braaksc,ceradsc,cogdx,dcfdx_lv,clinical_diagnosis,pathological_diagnosis,clinical_pathological_AD
0,R2626559,Rush,male,NaN,6.500000,ROSMAP-45310,1211411,ROS,1.0,12.0,...,85.549624,NaN,24.0,1.0,4.0,4.0,4.0,AD,No AD,False
1,R9936070,Rush,male,NaN,7.016667,ROSMAP-34387,2899847,MAP,1.0,14.0,...,74.450376,NaN,27.0,2.0,2.0,3.0,3.0,False,False,False
2,R2367199,Rush,male,NaN,4.333333,ROSMAP-69520,3713990,MAP,1.0,12.0,...,87.928816,NaN,30.0,4.0,2.0,1.0,1.0,NCI,False,False
3,R9891381,Rush,female,NaN,6.916667,ROSMAP-53306,3889845,MAP,0.0,13.0,...,90.000000,NaN,22.0,2.0,1.0,2.0,2.0,False,AD,False
4,R9033345,Rush,male,NaN,4.166667,ROSMAP-79585,6107196,MAP,1.0,15.0,...,90.000000,NaN,22.0,5.0,1.0,4.0,4.0,AD,AD,AD_with_Plaques
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,R9738414,Rush,female,NaN,9.250000,ROSMAP-90149,20976799,ROS,0.0,18.0,...,90.000000,NaN,19.0,2.0,4.0,2.0,2.0,False,No AD,False
510,R7737688,Rush,female,NaN,7.000000,NaN,69866926,MAP,0.0,13.0,...,84.104038,20.0,3.0,6.0,1.0,4.0,4.0,AD,AD,AD_with_Plaques
511,R7844746,Rush,male,NaN,0.866667,NaN,29286432,ROS,1.0,24.0,...,90.000000,NaN,29.0,5.0,2.0,2.0,2.0,False,False,False
512,R6692433,Rush,female,NaN,6.583333,NaN,48331728,MAP,0.0,14.0,...,82.715948,NaN,27.0,2.0,4.0,1.0,1.0,NCI,No AD,NCI_with_No_Plaques
513,R5309342,Rush,female,NaN,7.733333,NaN,10371937,MAP,0.0,18.0,...,81.032170,25.0,25.0,5.0,1.0,4.0,4.0,AD,AD,AD_with_Plaques

# Loading MetaData

In [13]:
meta_data = pd.read_csv('../../usman/Single_Cell_Microglia_Project/preprocessed_data/excitory_neurons/full_metadata_excitory_neurons_3_rds.csv',index_col = 0)
meta_data = meta_data.sort_values(by = ['cell_id'])
meta_data

,cell_id,orig.ident,nCount_RNA,nFeature_RNA,cell_type_high_resolution,subject,Pathologic_diagnosis_of_AD
1,AAACCCAAGAAGCTGC-25-7,ROSMAP,9149,3523,Exc L6 THEMIS NFIA,ROSMAP-43621,yes
2,AAACCCAAGAAGTCTA-5-2,ROSMAP,32459,7301,Exc L6 THEMIS NFIA,ROSMAP-96129,no
3,AAACCCAAGAAGTGTT-20-2,ROSMAP,38004,8389,Exc L6 THEMIS NFIA,ROSMAP-20769,no
4,AAACCCAAGAATTGTG-8-3,ROSMAP,39320,8621,Exc RELN CHD7,ROSMAP-37539,yes
5,AAACCCAAGACCCGCT-12-13,ROSMAP,61331,8627,Exc L6 THEMIS NFIA,ROSMAP-92445,yes
...,...,...,...,...,...,...,...
324761,TTTGTTGTCTGAGAGG-29-10,ROSMAP,780,603,Exc NRGN,ROSMAP-18695,yes
324762,TTTGTTGTCTGCGATA-3-4,ROSMAP,594,470,Exc RELN CHD7,ROSMAP-86649,no
324763,TTTGTTGTCTGGTTGA-13-9,ROSMAP,3737,1927,Exc RELN CHD7,ROSMAP-67297,yes
324764,TTTGTTGTCTGTCGTC-13-14,ROSMAP,37952,7179,Exc L6 THEMIS NFIA,ROSMAP-21259,no
324765,TTTGTTGTCTTTCAGT-19-9,ROSMAP,2633,1379,Exc RELN CHD7,ROSMAP-60910,yes

In [14]:
meta_data.cell_type_high_resolution.unique()

array(['Exc L6 THEMIS NFIA', 'Exc RELN CHD7', 'Exc NRGN', 'Exc L5/6 NP',
       'Exc L6 CT', 'Exc L5-6 RORB LINC02196', 'Exc L5/6 IT Car3',
       'Exc L6b', 'Exc L5 ET'], dtype=object)

In [15]:
try:
    meta_data['cell_id'] = meta_data['cell_id'].str.replace('-', '.')
except:
    print('probably not needed to do')
meta_data.head()

,cell_id,orig.ident,nCount_RNA,nFeature_RNA,cell_type_high_resolution,subject,Pathologic_diagnosis_of_AD
1,AAACCCAAGAAGCTGC.25.7,ROSMAP,9149,3523,Exc L6 THEMIS NFIA,ROSMAP-43621,yes
2,AAACCCAAGAAGTCTA.5.2,ROSMAP,32459,7301,Exc L6 THEMIS NFIA,ROSMAP-96129,no
3,AAACCCAAGAAGTGTT.20.2,ROSMAP,38004,8389,Exc L6 THEMIS NFIA,ROSMAP-20769,no
4,AAACCCAAGAATTGTG.8.3,ROSMAP,39320,8621,Exc RELN CHD7,ROSMAP-37539,yes
5,AAACCCAAGACCCGCT.12.13,ROSMAP,61331,8627,Exc L6 THEMIS NFIA,ROSMAP-92445,yes

# Merging CLinical Data and Single cell Data

In [16]:
meta_data = pd.merge(meta_data,clinical_data[['subject','clinical_pathological_AD']], on = 'subject', how = 'left')

meta_data

,cell_id,orig.ident,nCount_RNA,nFeature_RNA,cell_type_high_resolution,subject,Pathologic_diagnosis_of_AD,clinical_pathological_AD
0,AAACCCAAGAAGCTGC.25.7,ROSMAP,9149,3523,Exc L6 THEMIS NFIA,ROSMAP-43621,yes,AD_with_Plaques
1,AAACCCAAGAAGTCTA.5.2,ROSMAP,32459,7301,Exc L6 THEMIS NFIA,ROSMAP-96129,no,NCI_with_No_Plaques
2,AAACCCAAGAAGTCTA.5.2,ROSMAP,32459,7301,Exc L6 THEMIS NFIA,ROSMAP-96129,no,NCI_with_No_Plaques
3,AAACCCAAGAAGTGTT.20.2,ROSMAP,38004,8389,Exc L6 THEMIS NFIA,ROSMAP-20769,no,False
4,AAACCCAAGAAGTGTT.20.2,ROSMAP,38004,8389,Exc L6 THEMIS NFIA,ROSMAP-20769,no,False
...,...,...,...,...,...,...,...,...
409273,TTTGTTGTCTGAGAGG.29.10,ROSMAP,780,603,Exc NRGN,ROSMAP-18695,yes,False
409274,TTTGTTGTCTGCGATA.3.4,ROSMAP,594,470,Exc RELN CHD7,ROSMAP-86649,no,False
409275,TTTGTTGTCTGGTTGA.13.9,ROSMAP,3737,1927,Exc RELN CHD7,ROSMAP-67297,yes,False
409276,TTTGTTGTCTGTCGTC.13.14,ROSMAP,37952,7179,Exc L6 THEMIS NFIA,ROSMAP-21259,no,NCI_with_No_Plaques
409277,TTTGTTGTCTTTCAGT.19.9,ROSMAP,2633,1379,Exc RELN CHD7,ROSMAP-60910,yes,AD_with_Plaques

In [17]:
meta_data = meta_data[meta_data.cell_id.isin(data.index.tolist())]
meta_data

,cell_id,orig.ident,nCount_RNA,nFeature_RNA,cell_type_high_resolution,subject,Pathologic_diagnosis_of_AD,clinical_pathological_AD
15,AAACCCAAGAGGCCAT.35.2,ROSMAP,27064,6623,Exc L6 CT,ROSMAP-40612,yes,False
16,AAACCCAAGAGGCCAT.35.2,ROSMAP,27064,6623,Exc L6 CT,ROSMAP-40612,yes,False
32,AAACCCAAGCCTCAAT.8.8,ROSMAP,15841,4588,Exc L6 CT,ROSMAP-16216,yes,AD_with_Plaques
33,AAACCCAAGCCTGAAG.5.6,ROSMAP,22493,5867,Exc L6 CT,ROSMAP-77693,yes,AD_with_Plaques
43,AAACCCAAGCTCCATA.21.8,ROSMAP,31367,6886,Exc L6 CT,ROSMAP-23283,yes,False
...,...,...,...,...,...,...,...,...
409234,TTTGTTGTCCGTGCGA.10.7,ROSMAP,11205,3819,Exc L6 CT,ROSMAP-86231,yes,AD_with_Plaques
409241,TTTGTTGTCCTTCGAC.16.2,ROSMAP,24150,6654,Exc L6 CT,ROSMAP-77461,no,NCI_with_No_Plaques
409242,TTTGTTGTCCTTCGAC.16.2,ROSMAP,24150,6654,Exc L6 CT,ROSMAP-77461,no,NCI_with_No_Plaques
409254,TTTGTTGTCGGTCTAA.20.5,ROSMAP,30244,7152,Exc L6 CT,ROSMAP-72125,no,False
409256,TTTGTTGTCGTCAAAC.2.5,ROSMAP,35363,7319,Exc L6 CT,ROSMAP-53781,yes,False

In [18]:
meta_data = meta_data[meta_data.clinical_pathological_AD != 'False']
meta_data
meta_data.clinical_pathological_AD.value_counts()

clinical_pathological_AD
NCI_with_No_Plaques    6683
AD_with_Plaques        4986
Name: count, dtype: int64

In [19]:
meta_data_NCI = meta_data[meta_data.clinical_pathological_AD == 'NCI_with_No_Plaques'][0:min(meta_data.clinical_pathological_AD.value_counts().tolist())]
meta_data_AD = meta_data[meta_data.clinical_pathological_AD == 'AD_with_Plaques'][0:min(meta_data.clinical_pathological_AD.value_counts().tolist())]

In [20]:
meta_data = pd.concat([meta_data_NCI,meta_data_AD])
meta_data.set_index('cell_id',inplace = True)
meta_data.sort_index(inplace= True)
meta_data

,orig.ident,nCount_RNA,nFeature_RNA,cell_type_high_resolution,subject,Pathologic_diagnosis_of_AD,clinical_pathological_AD
cell_id,,,,,,,
AAACCCAAGCCTCAAT.8.8,ROSMAP,15841,4588,Exc L6 CT,ROSMAP-16216,yes,AD_with_Plaques
AAACCCAAGCCTGAAG.5.6,ROSMAP,22493,5867,Exc L6 CT,ROSMAP-77693,yes,AD_with_Plaques
AAACCCAGTCGGCACT.6.13,ROSMAP,40972,7918,Exc L6 CT,ROSMAP-13381,no,NCI_with_No_Plaques
AAACCCAGTGCGTCGT.13.12,ROSMAP,3082,1743,Exc L6 CT,ROSMAP-99585,yes,AD_with_Plaques
AAACCCAGTGGCAGAT.18.6,ROSMAP,24588,6442,Exc L6 CT,ROSMAP-37253,yes,AD_with_Plaques
...,...,...,...,...,...,...,...
TTTGTTGAGCTAGCCC.5.6,ROSMAP,13563,4848,Exc L6 CT,ROSMAP-77693,yes,AD_with_Plaques
TTTGTTGCATCGTGGC.16.11,ROSMAP,10209,3948,Exc L6 CT,ROSMAP-53808,yes,AD_with_Plaques
TTTGTTGCATCGTGGC.16.11,ROSMAP,10209,3948,Exc L6 CT,ROSMAP-53808,yes,AD_with_Plaques
TTTGTTGTCCGTCACT.10.7,ROSMAP,32325,6887,Exc L6 CT,ROSMAP-86231,yes,AD_with_Plaques
TTTGTTGTCCGTGCGA.10.7,ROSMAP,11205,3819,Exc L6 CT,ROSMAP-86231,yes,AD_with_Plaques

In [21]:
meta_data.clinical_pathological_AD.value_counts()

clinical_pathological_AD
AD_with_Plaques        4986
NCI_with_No_Plaques    4986
Name: count, dtype: int64

In [22]:
data = data.loc[meta_data.index,]
data

ensemble_gene_name,ENSG00000101198,ENSG00000101199,ENSG00000101203,ENSG00000101204,ENSG00000281151,ENSG00000101210,ENSG00000125534,ENSG00000101213,ENSG00000125508,ENSG00000125531,...,ENSG00000177508,ENSG00000261803,ENSG00000283304,ENSG00000245694,ENSG00000176842,ENSG00000159387,ENSG00000087245,ENSG00000260135,ENSG00000087253,ENSG00000256812
cell_id,,,,,,,,,,,,,,,,,,,,,
AAACCCAAGCCTCAAT.8.8,1,0,0,0,6,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAACCCAAGCCTGAAG.5.6,0,1,0,0,3,2,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAACCCAGTCGGCACT.6.13,0,3,0,0,7,3,1,0,0,0,...,0,0,0,0,0,0,0,0,2,0
AAACCCAGTGCGTCGT.13.12,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAACCCAGTGGCAGAT.18.6,0,0,0,0,3,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTTGAGCTAGCCC.5.6,0,0,0,2,1,3,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
TTTGTTGCATCGTGGC.16.11,0,0,0,0,4,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTTGTTGCATCGTGGC.16.11,0,0,0,0,4,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTTGTTGTCCGTCACT.10.7,0,1,0,0,3,3,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTTGTTGTCCGTGCGA.10.7,0,1,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
y = meta_data.clinical_pathological_AD.tolist()

In [24]:
X = data

In [25]:
from sklearn.model_selection import train_test_split


# Step 1: Split data into training and temporary dataset (which will be further split into testing and validation)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.40, random_state=42)  # 40% of data will be split into testing and validation

# Step 2: Split the temporary dataset into testing and validation
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.50, random_state=42)  # 50% of the temporary set will be for validation and 50% for testing

# Now you have: 
# X_train, y_train - Training data
# X_val, y_val - Validation data
# X_test, y_test - Testing data

In [26]:
X_train

ensemble_gene_name,ENSG00000101198,ENSG00000101199,ENSG00000101203,ENSG00000101204,ENSG00000281151,ENSG00000101210,ENSG00000125534,ENSG00000101213,ENSG00000125508,ENSG00000125531,...,ENSG00000177508,ENSG00000261803,ENSG00000283304,ENSG00000245694,ENSG00000176842,ENSG00000159387,ENSG00000087245,ENSG00000260135,ENSG00000087253,ENSG00000256812
cell_id,,,,,,,,,,,,,,,,,,,,,
ACAGCCGTCGTCTACC.9.14,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CGAGCACCATAGACTC.20.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAGGCAGTCCTCATTA.26.0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CTCAGTCCAGACGGAT.26.6,0,0,0,0,5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TAGCCGGCAGAGCCAA.5.1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CTTTCAACATCCGCGA.25.11,0,0,0,1,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CTCAGTCCAATTTCTC.26.6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CTCTGGTTCGAGATAA.30.10,0,1,0,2,0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACCGTTCTCGATTGAC.32.5,0,0,0,0,4,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GGGATGAAGATACATG.10.4,0,0,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
y_train = pd.DataFrame(y_train)
y_test = pd.DataFrame(y_test)
y_val = pd.DataFrame(y_val)

In [28]:
y_val

                        0
0     NCI_with_No_Plaques
1         AD_with_Plaques
2     NCI_with_No_Plaques
3     NCI_with_No_Plaques
4     NCI_with_No_Plaques
...                   ...
1989  NCI_with_No_Plaques
1990      AD_with_Plaques
1991  NCI_with_No_Plaques
1992  NCI_with_No_Plaques
1993  NCI_with_No_Plaques

[1994 rows x 1 columns]

In [29]:
X_train.to_csv('./Preprocessed_data/excitory_neurons/Exc_L6b/train.csv')
X_test.to_csv('./Preprocessed_data/excitory_neurons/Exc_L6b/test.csv')
X_val.to_csv('./Preprocessed_data/excitory_neurons/Exc_L6b/val.csv')

# AD_with_Plaques:1
# NCI_with_No_Plaques: 0

In [30]:


try:
    diagnosis_mapping = {'AD_with_Plaques': 1, 'NCI_with_No_Plaques': 0}
    y_test['diagnosis_binary'] = y_test[0].map(diagnosis_mapping)
    
    # Display the first few rows to verify the mapping
    print(y_test.head())
    y_test.drop(columns=[0], inplace=True)
    y_test

except:
    print('Previously Run Before')

                     0  diagnosis_binary
0      AD_with_Plaques                 1
1  NCI_with_No_Plaques                 0
2      AD_with_Plaques                 1
3      AD_with_Plaques                 1
4  NCI_with_No_Plaques                 0

In [31]:


try:
    diagnosis_mapping = {'AD_with_Plaques': 1, 'NCI_with_No_Plaques': 0}
    y_train['diagnosis_binary'] = y_train[0].map(diagnosis_mapping)
    
    # Display the first few rows to verify the mapping
    
    y_train.drop(columns=[0], inplace=True)
    y_train

except:
    print('Previously Run Before')
print(y_train.head())

   diagnosis_binary
0                 0
1                 0
2                 1
3                 1
4                 1

In [32]:

try:
    diagnosis_mapping = {'AD_with_Plaques': 1, 'NCI_with_No_Plaques': 0}
    y_val['diagnosis_binary'] = y_val[0].map(diagnosis_mapping)
    # Display the first few rows to verify the mapping
    y_val.drop(columns=[0], inplace=True)
    y_val

except:
    print('Previously Run Before')
print(y_val.head())

   diagnosis_binary
0                 0
1                 1
2                 0
3                 0
4                 0

In [33]:
!pwd

/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network

In [34]:
y_train.rename(columns = {'diagnosis_binary':'diagnosis'}, inplace=True)
y_test.rename(columns = {'diagnosis_binary':'diagnosis'}, inplace=True)
y_val.rename(columns = {'diagnosis_binary':'diagnosis'}, inplace=True)

In [35]:
y_train.head()

   diagnosis
0          0
1          0
2          1
3          1
4          1

In [36]:
y_val.head()

   diagnosis
0          0
1          1
2          0
3          0
4          0

In [37]:
y_test.head()

   diagnosis
0          1
1          0
2          1
3          1
4          0

In [38]:
y_val.to_csv('./Preprocessed_data/excitory_neurons/Exc_L6b/y_val.csv', index = False)
y_test.to_csv('./Preprocessed_data/excitory_neurons/Exc_L6b/y_test.csv', index = False)
y_train.to_csv('./Preprocessed_data/excitory_neurons/Exc_L6b/y_train.csv', index = False)

In [39]:
meta_data.to_csv('./Preprocessed_data/excitory_neurons/Exc_L6b/meta_data.csv', index = False)

In [40]:
!pwd

/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network

In [41]:
y_train

      diagnosis
0             0
1             0
2             1
3             1
4             1
...         ...
5978          0
5979          1
5980          1
5981          1
5982          1

[5983 rows x 1 columns]

In [42]:
train = pd.read_csv('./Preprocessed_data/excitory_neurons/Exc_L5_ET/train.csv',index_col=0)
train

,ENSG00000101198,ENSG00000101199,ENSG00000101203,ENSG00000101204,ENSG00000281151,ENSG00000101210,ENSG00000125534,ENSG00000101213,ENSG00000125508,ENSG00000125531,...,ENSG00000177508,ENSG00000261803,ENSG00000283304,ENSG00000245694,ENSG00000176842,ENSG00000159387,ENSG00000087245,ENSG00000260135,ENSG00000087253,ENSG00000256812
cell_id,,,,,,,,,,,,,,,,,,,,,
GGAGATGCAGACCAAG.34.2,0,2,0,0,4,3,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
TCAACGAGTGTTTGGT.22.0,0,1,0,2,1,1,4,0,0,0,...,0,0,0,1,0,0,0,0,0,0
TTCAGGAGTTGTTGCA.26.3,0,0,0,0,1,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GTCCTCACAACAGCCC.16.2,0,0,0,1,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CCGTACTCATTGGTAC.38.1,0,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GTAACTGGTCATACTG.15.1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GTCACGGGTCCTCATC.13.11,0,2,0,0,3,4,0,0,0,0,...,0,0,0,1,0,0,0,0,3,0
TCGAACAGTCATATGC.28.2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GACTCAAGTTAATGAG.33.2,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
GTCAAGTGTCAAAGCG.35.1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
val = pd.read_csv('./Preprocessed_data/excitory_neurons/Exc_L5_ET/val.csv',index_col=0)
val

,ENSG00000101198,ENSG00000101199,ENSG00000101203,ENSG00000101204,ENSG00000281151,ENSG00000101210,ENSG00000125534,ENSG00000101213,ENSG00000125508,ENSG00000125531,...,ENSG00000177508,ENSG00000261803,ENSG00000283304,ENSG00000245694,ENSG00000176842,ENSG00000159387,ENSG00000087245,ENSG00000260135,ENSG00000087253,ENSG00000256812
cell_id,,,,,,,,,,,,,,,,,,,,,
GAGTTTGTCCACGGAC.32.9,0,3,1,0,1,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AACAAAGAGAAGATCT.9.11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CTCGAGGTCCCTCAGT.5.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CTCAGTCCAGGCCTGT.5.6,0,1,0,0,1,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AGTACTGCATAAGCAA.11.11,0,0,0,0,3,4,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CCGCAAGAGTCGAAAT.10.4,0,1,0,0,6,19,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CTGAAACTCCGCGTTT.36.1,0,0,0,0,2,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GGGTAGAGTTCTTAGG.13.12,0,3,0,1,4,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ATCACTTAGTTGGCTT.45.2,0,0,0,0,2,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GAGTGTTGTTCTGACA.18.6,0,0,0,2,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
test = pd.read_csv('./Preprocessed_data/excitory_neurons/Exc_L5_6_NP/test.csv',index_col=0)
test

,ENSG00000101198,ENSG00000101199,ENSG00000101203,ENSG00000101204,ENSG00000281151,ENSG00000101210,ENSG00000125534,ENSG00000101213,ENSG00000125508,ENSG00000125531,...,ENSG00000177508,ENSG00000261803,ENSG00000283304,ENSG00000245694,ENSG00000176842,ENSG00000159387,ENSG00000087245,ENSG00000260135,ENSG00000087253,ENSG00000256812
cell_id,,,,,,,,,,,,,,,,,,,,,
CCTTGTGCATTCGATG.18.11,0,0,0,0,3,5,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ATCGTAGCATGTCTAG.23.6,0,0,0,0,4,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACCTGAAGTGCCTACG.12.9,0,0,0,1,2,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GTGTGGCCAGAGGCTA.6.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
TTAGTCTAGTACAGCG.34.2,0,0,0,0,6,2,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AACCACACACGAGGAT.8.14,0,0,0,1,4,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ATATCCTAGTAATTGG.9.11,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AGGTCATGTTGTGTAC.30.10,0,0,0,0,2,8,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GATCCCTCACCACATA.25.7,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CATTCGCAGATGCGAC.23.1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [45]:
pd.read_csv('./Preprocessed_data/excitory_neurons/Exc_L5_6_NP/y_test.csv')

      diagnosis
0             0
1             1
2             1
3             0
4             1
...         ...
1437          1
1438          0
1439          1
1440          1
1441          0

[1442 rows x 1 columns]

In [46]:
pd.read_csv('./Preprocessed_data/excitory_neurons/Exc_L5_6_NP/y_train.csv')

      diagnosis
0             0
1             0
2             0
3             1
4             0
...         ...
4319          0
4320          0
4321          1
4322          1
4323          1

[4324 rows x 1 columns]

In [47]:
pd.read_csv('./Preprocessed_data/excitory_neurons/Exc_L5_6_NP/y_val.csv')

      diagnosis
0             1
1             1
2             1
3             1
4             1
...         ...
1437          1
1438          0
1439          1
1440          0
1441          0

[1442 rows x 1 columns]

In [48]:
!pwd

/12tb_dsk1/danish/Pytorch_Biologically_Informed_Neural_Network